import React from "react";
import {
  AisleArrival,
  BackSeats,
  ExitPostButton,
  Column2Arrival,
  ColumnExit,
  ReferencePost,
  RowSeats,
  SubtitleReturn,
} from "./ExitFlightStyled";

const ExitFlight = () => {
  return (
    <>
      <div>
        <div>
          <h1>Vuelo de Salida</h1>
          <button>Cambiar vuelo</button>
        </div>
        <h2>Martes 30 nov 2021</h2>
        <h4>Cd. Mexico a Culiacan(ADZ)</h4>
        <p>Selecciona tus Asientos</p>
      </div>

      <ReferencePost>
        <ColumnExit>
          <RowSeats>
            <AisleArrival>A</AisleArrival>
            <AisleArrival>B</AisleArrival>
            <AisleArrival>C</AisleArrival>
          </RowSeats>
        </ColumnExit>
        <ColumnExit>
          <AisleArrival></AisleArrival>
        </ColumnExit>
        <ColumnExit>
          <RowSeats>
            <AisleArrival>D</AisleArrival>
            <AisleArrival>E</AisleArrival>
            <AisleArrival>F</AisleArrival>
          </RowSeats>
        </ColumnExit>
      </ReferencePost>
      <SubtitleReturn>
        <h5>Salida Rapida</h5>
      </SubtitleReturn>
      <BackSeats>
        <ColumnExit>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
        </ColumnExit>
        <Column2Arrival>
          <ExitPostButton>1</ExitPostButton>
          <ExitPostButton>3</ExitPostButton>
          <ExitPostButton>4</ExitPostButton>
          <ExitPostButton>2</ExitPostButton>
          <ExitPostButton>5</ExitPostButton>
        </Column2Arrival>
        <ColumnExit>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
        </ColumnExit>
      </BackSeats>
      <SubtitleReturn>
        <h5>Estándar</h5>
      </SubtitleReturn>
      <BackSeats>
        <ColumnExit>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
        </ColumnExit>
        <Column2Arrival>
          <AisleArrival>6</AisleArrival>
          <AisleArrival>7</AisleArrival>
          <AisleArrival>8</AisleArrival>
          <AisleArrival>9</AisleArrival>
          <AisleArrival>10</AisleArrival>
        </Column2Arrival>
        <ColumnExit>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
          <RowSeats>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
            <ExitPostButton></ExitPostButton>
          </RowSeats>
        </ColumnExit>
      </BackSeats>
    </>
  );
};

export default ExitFlight;
