import React from "react";
import {
  AisleArrival,
  BackSeats,
  ReturnPostButton,
  Column2Arrival,
  Column,
  ReferencePost,
  RowSeats,
  SubtitleReturn,
} from "./ReturnFlightStyled";

const ReturnFlight = () => {
  return (
    <>
      <div>
        <div>
          <h1>Vuelo de Regreso</h1>
          <button>Cambiar vuelo</button>
        </div>
        <h2>Miercoles 8 dic 2023</h2>
        <h4>Culiacan a cd. mex(ADZ)</h4>
        <p>Selecciona tus Asientos</p>
      </div>

      <ReferencePost>
        <Column>
          <RowSeats>
            <AisleArrival>A</AisleArrival>
            <AisleArrival>B</AisleArrival>
            <AisleArrival>C</AisleArrival>
          </RowSeats>
        </Column>
        <Column>
          <AisleArrival></AisleArrival>
        </Column>
        <Column>
          <RowSeats>
            <AisleArrival>D</AisleArrival>
            <AisleArrival>E</AisleArrival>
            <AisleArrival>F</AisleArrival>
          </RowSeats>
        </Column>
      </ReferencePost>
      <SubtitleReturn>
        <h5>Salida Rapida</h5>
      </SubtitleReturn>
      <BackSeats>
        <Column>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
        </Column>
        <Column2Arrival>
          <ReturnPostButton>1</ReturnPostButton>
          <ReturnPostButton>3</ReturnPostButton>
          <ReturnPostButton>4</ReturnPostButton>
          <ReturnPostButton>2</ReturnPostButton>
          <ReturnPostButton>5</ReturnPostButton>
        </Column2Arrival>
        <Column>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
        </Column>
      </BackSeats>
      <SubtitleReturn>
        <h5>Estándar</h5>
      </SubtitleReturn>
      <BackSeats>
        <Column>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
        </Column>
        <Column2Arrival>
          <AisleArrival>6</AisleArrival>
          <AisleArrival>7</AisleArrival>
          <AisleArrival>8</AisleArrival>
          <AisleArrival>9</AisleArrival>
          <AisleArrival>10</AisleArrival>
        </Column2Arrival>
        <Column>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
          <RowSeats>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
            <ReturnPostButton></ReturnPostButton>
          </RowSeats>
        </Column>
      </BackSeats>
    </>
  );
};

export default ReturnFlight;
